# Generated by Django 4.1.7 on 2023-03-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="numRviews",
            new_name="numReviews",
        ),
    ]
